# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycosites', '0004_auto_20151202_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniProtKB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('sequence', models.CharField(max_length=10000000000)),
            ],
        ),
    ]
