# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycosites', '0005_uniprotkb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=500)),
            ],
        ),
    ]
